model: 
  name: "meta-llama/Meta-Llama-3-8B-Instruct"

data:
  path: "data/MedMCQA"
  num_parts: 4 # Amounts to 45707 samples per part
  part_idx: 4
  num_samples: 290 # -1 for all samples, otherwise specify the number of samples to use from the split

task:
  name: "conflict_planting"
  prompt: "utils/prompts/conflict_planting.txt"

planting:
  exp_only: true
  overwrite: true
  allow_inv_mod_answ: true
  allow_id_mod_answ: false
  save_mod_questions: false
  save_mod_answers: true
  save_mod_explanations: true
