roberta: FacebookAI/roberta-large
bigbird: google/bigbird-roberta-large
longformer: allenai/longformer-large-4096
modernBERT: answerdotai/ModernBERT-large
gpt2: openai-community/gpt2
rwkv: RWKV/RWKV7-Goose-World3-1.5B-HF